### ISSUE TITLE
Wii U Pro Controller support

### ISSUE THREAD

**Issue by niuus** [raz0red/wii-mednafen#60] opened 2019-11-26 21:36 UTC
As the title implies, hoping that this useful feature can reach WiiMednafen, as it did with Wii7800 =D

**Comment by chrissmith-mcafee** [comment] 2019-11-27 21:11
Sounds good. 

I will try to get a build out for you to test in the next couple of days.

**Comment by niuus** [comment] 2019-11-28 01:36
> Sounds good.
> 
> I will try to get a build out for you to test in the next couple of days.
Thanks in advance!

**Comment by raz0red** [comment] 2019-11-28 05:16
Here is a build. Just unzip into the existing "APPS/wiimednafen" directory.
I did very little testing, so let my know if you see any issues.

[boot.zip](https://github.com/raz0red/wii-mednafen/files/3899965/boot.zip)

I will be committing my changes later tonight. Once I get some time to adequately test it, I will put a new version out (or maybe another pre-release version).

**Comment by niuus** [comment] 2019-11-28 14:02
> Here is a build. Just unzip into the existing "APPS/wiimednafen" directory.
> I did very little testing, so let my know if you see any issues.
> 
> [boot.zip](https://github.com/raz0red/wii-mednafen/files/3899965/boot.zip)
> 
> I will be committing my changes later tonight. Once I get some time to adequately test it, I will put a new version out (or maybe another pre-release version).

Testing! Will report back.

**Comment by rogerioronin** [comment] 2019-11-28 14:21
Is Niuss possible to implement support for Playstation 3 and Xbox control on WiiMednafen, same as on Snes9x RX?

**Comment by niuus** [comment] 2019-11-28 20:24
> Here is a build. Just unzip into the existing "APPS/wiimednafen" directory.
> I did very little testing, so let my know if you see any issues.
> 
> I will be committing my changes later tonight. Once I get some time to adequately test it, I will put a new version out (or maybe another pre-release version).

I tested every single console. Happy to tell you that Wii U Pro Controller works fine =D

The only issues i could detect:
- Turbo CD/PC Engine CD is not working. Going back to previous version works okey.
- I think 6 button controller doesn't seem to be entirely working on the Genesis/Mega Drive (6 buttons worked perfect on Turbografx 16, in case you're curious). Test game was Street Fighter II Champion Edition, A B C work, while X Y Z do not.

**Comment by niuus** [comment] 2019-11-28 20:36
> Is Niuss possible to implement support for Playstation 3 and Xbox control on WiiMednafen, same as on Snes9x RX?

Wish i could give it a try, but i'll be work-traveling in some days, so i won't be able to deploy a new version of devkit anytime soon, and even then i have to figure out what happened with the 360 controller code that makes loading though a USB device hang (a workaround can be done by loading the emulator through any SD and using USB for ROMS). The good thing is that the code is in Snes9x RX Github, maybe someday could be used in the future for this!

**Comment by chrissmith-mcafee** [comment] 2019-11-28 20:49
> > Here is a build. Just unzip into the existing "APPS/wiimednafen" directory.
> > I did very little testing, so let my know if you see any issues.
> > I will be committing my changes later tonight. Once I get some time to adequately test it, I will put a new version out (or maybe another pre-release version).
> 
> I tested every single emulated console on WiiMednafen. Happy to tell you that Wii U Pro Controller works fine =D
> 
> The only issues i could detect:
> 
> * Turbo CD/PC Engine CD is not working. Going back to previous version works okey.
> * I think 6 button controller doesn't seem to be entirely working on the Genesis/Mega Drive (6 buttons worked perfect on Turbografx 16, in case you're curious). My only test game was Street Fighter II Champion Edition, A B C work, while X Y Z do not. The controller is properly detected in-game when you open the game's Options menu.

Thanks a lot for testing!

Odd that PCE CD is not working, none of that code has changed. I will dig into it later today and let you know what I find.

Not sure about Genesis either, I will dig into that as well.

Thanks again,
Chris

**Comment by raz0red** [comment] 2019-11-29 02:07
Still digging into the PCE CD issue. It appears to be due to memory corruption that is occurring when CDs are loaded. Pretty odd that it never occurred in the previous versions of devkit. At any rate, I will keep digging and try to track it down...

**Comment by niuus** [comment] 2019-11-29 15:57
> Odd that PCE CD is not working, none of that code has changed. I will dig into it later today and let you know what I find.
> 
> Not sure about Genesis either, I will dig into that as well.
> 


> Still digging into the PCE CD issue. It appears to be due to memory corruption that is occurring when CDs are loaded. Pretty odd that it never occurred in the previous versions of devkit. At any rate, I will keep digging and try to track it down...

A long time ago i noticed that newer devkitPro versions tend to unintentionally drop performance, or break a thing or two sometimes, this was more evident in Snes9x, (Final Fantasy VI crashed when entering a fight, B.O.B. had some weird lines on the vertical borders, etc.). Maybe that's whats happening here?

I'll be around for more tests that you might need in the future.

Thanks for your efforts. WiiMednafen is still rocking the boat after all these years =D

**Comment by raz0red** [comment] 2019-11-29 17:22
Thanks!

I spent a long time last night attempting to determine the cause of the issue, but unfortunately haven't made much progress. I was hoping it would be something straight-forward, but it is pretty odd. It almost appears like the stack pointer is getting corrupted, as it gets stuck looping in a portion of code that isn't a loop. 

The odd part is, the code isn't necessarily all that complex. Other similar code paths do not exhibit the behavior (PC-FX and PCE roms). 

At any rate, I will keep digging. If nothing else, will be interesting to see what was causing it.

**Comment by raz0red** [comment] 2019-11-29 23:26
Well, I was able to get it working. I have quite a bit of cleanup to do, but will try to get another test build out later tonight.

**Comment by raz0red** [comment] 2019-11-30 07:33
> * I think 6 button controller doesn't seem to be entirely working on the Genesis/Mega Drive (6 buttons worked perfect on Turbografx 16, in case you're curious). My only test game was Street Fighter II Champion Edition, A B C work, while X Y Z do not. The controller is properly detected in-game when you open the game's Options menu.

I tested this and it occurs on both the current (0.2-pre) and a recent build. If you wouldn't mind, could you please submit a separate issue? 

Thanks a lot for finding it!

**Comment by niuus** [comment] 2019-11-30 14:27
> > * I think 6 button controller doesn't seem to be entirely working on the Genesis/Mega Drive (6 buttons worked perfect on Turbografx 16, in case you're curious). My only test game was Street Fighter II Champion Edition, A B C work, while X Y Z do not. The controller is properly detected in-game when you open the game's Options menu.
> 
> I tested this and it occurs on both the current (0.2-pre) and a recent build. If you wouldn't mind, could you please submit a separate issue?
> 
> Thanks a lot for finding it!

Sure!

**Comment by raz0red** [comment] 2019-12-01 20:05
Marking this issue as closed, as the WiiU Pro Controller does work on 0.3-SNAPSHOT builds.

However, I created a new issue (#69) to track stability issues with newer builds.

**Closed** 2019-12-01 20:10 UTC
Labels: enhancement
